/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RS232.h"
#include "RFID.h"
#include "PSOC.h"
#include "Bluetooth.h"
#include "Surtidor.h"
#include "Select1_RFID_aliases.h"
#include "Select1_RFID.h"
#include "Enable_RFid_aliases.h"
#include "Enable_RFid.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "Select1_RS232_aliases.h"
#include "Select1_RS232.h"
#include "Select0_RFID_aliases.h"
#include "Select0_RFID.h"
#include "Select0_RS232_aliases.h"
#include "Select0_RS232.h"
#include "Botones_aliases.h"
#include "Botones.h"
#include "Psoc_status_aliases.h"
#include "Psoc_status.h"
#include "IB2_aliases.h"
#include "IB2.h"
#include "IB1_aliases.h"
#include "IB1.h"
#include "Clock_1.h"
#include "EEPROM.h"
#include "Led_aliases.h"
#include "Led.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "RS232_IntClock.h"
#include "RFID_IntClock.h"
#include "PSOC_IntClock.h"
#include "Bluetooth_IntClock.h"
#include "Surtidor_IntClock.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

